server:
  port: 8081

cloud:
  aws:
    region:
      static: us-east-2
      auto: false
    credentials:
      access-key: <yourkey>
      secret-key: <your key>
    end-point:
      uri: <your uri>

